column_renames = {
    'Unnamed: 0': "_id", 
     'SHIPPER': "shipper", 
     'SHIPPER.ADDRESS': "shipper_address", 
     'CONSIGNEE': "consignee",
       'CONSIGNEE.ADDRESS': "consignee_address", 
     'ZIPCODE': "consignee_zipcode", 
     'NOTIFY': "notify", 
     'NOTIFY.ADDRESS': "notify_address",
       'BILL.OF.LADING': "bill_of_lading", 
     'ARRIVAL.DATE': "arrival_date", 
     'WEIGHT..LB.': "weight_lb", 
     'WEIGHT..KG.': "weight_kg",
       'US.PORT': "us_port", 
     'QUANTITY': "quantity", 
     'Q.UNIT': "quantity_unit", 
     'MEASUREMENT': "measurement", 
     'M.UNIT': "measurement_unit",
       'SHIP.REGISTERED.IN': "ship_registered_in", 
     'VESSEL.NAME': "vessel_name", 
     'CONTAINER.COUNT': "container_count",
       'PRODUCT.DETAILS': "product_details", 
     'MARKS.AND.NUMBERS': "marks_and_numbers", 
     'COUNTRY.OF.ORIGIN': "country_of_origin",
       'DISTRIBUTION.PORT': "distribution_port", 
     'CARRIER.CODE': "carrier_code", 
     'CARRIER.NAME': "carrier_name", 
     'CARRIER.ADDRESS': "carrier_address",
       'CARRIER.CITY': "carrier_city", 
     'CARRIER.STATE': "carrier_state", 
     'CARRIER.ZIP': "carrier_zip"
}

vals_to_keep_dict = {
   "shipper":[
      "-NOT AVAILABLE-",
      "nan",
      "BANANERA NACIONAL S A",
      "APM GLOBAL LOGISTICS BANGLADESH LTD",
      "CARIBBEAN PINEAPPLE EXPORT SA",
      "BEIJING KANG JIE KONG INTERNATIONAL",
      "DE WELL CONTAINER SHIPPING INC.",
      "DAMCO SHENZHEN O/B",
      "SAM SOL, S.A.",
      "COSENTINO S.A",
      "DAMCO CHINA LIMITED O/B",
      "UPALA AGRICOLA S A",
      "MITSUBISHI ELECTRIC LOGISTICS CORP.",
      "PT. SAM SAN INTERNATIONAL",
      "GHIM LI CAMBODIA PTE LTD",
      "DAMCO ON BEHALF OF",
      "STAR KIST SAMOA, INC",
      "COSENTINO S.A.",
      "LY FURNITURE SDN BHD",
      "TROPICAL RICA INTERNATIONAL TRI S A",
      "DAMCO INDIA PVT LTD",
      "V & M DEUTSCHLAND GMBH",
      "DAVID DEL CURTO S.A.",
      "ALEX APPAREL.",
      "EXPORTADORA RIO BLANCO LTDA."
   ],
   "consignee":[
      "-NOT AVAILABLE-",
      "WAL-MART CANADA CORP.",
      "WALMART STORES INC",
      "WAL-MART STORES, INC.",
      "WAL-MART STORE,INC.",
      "WAL-MART STORES INCORPORATED",
      "CROWN MARK INC.",
      "UNTO THE ORDER OF",
      "COMERCIALIZADORA MEXICO AMERICANA",
      "C&C NORTH AMERICA DBA COSENTINO NOR",
      "WALMART STORES INC.",
      "WAL-MART STORES INC. USA",
      "SPC GLOBAL LLC",
      "TO THE ORDER OF",
      "DE WELL CONTAINER SHIPPING,INC.",
      "YUSEN LOGISTICS AMERICAS INC.",
      "CROWN MARK INC",
      "VALLOUREC & MANNESMANN TUBES",
      "STARKIST CO.",
      "WAL-MART STORES, INC, USA",
      "COMERCIALIZADORA MEXICO AMERICANA S",
      "CAMERON INTERNATIONAL CORPORATION",
      "C&C NORTH AMERICA DBA",
      "VERTICAL MFG",
      "TO ORDER"
   ],
   "us_port":[
      "Long Beach, California",
      "Norfolk, Virginia",
      "Savannah, Georgia",
      "Los Angeles, California",
      "Houston, Texas",
      "Seattle, Washington",
      "New York/Newark Area, Newark, New Jersey",
      "Tacoma, Washington",
      "Charleston, South Carolina",
      "Miami, Florida",
      "Oakland, California",
      "Philadelphia, Pennsylvania",
      "San Juan, Puerto Rico",
      "New York, New York",
      "New Orleans, Louisiana",
      "Port Everglades, Florida",
      "Jacksonville, Florida",
      "Baltimore, Maryland",
      "Boston, Massachusetts",
      "Everett, Washington",
      "Wilmington, Delaware",
      "Wilmington, North Carolina",
      "Tampa, Florida",
      "Chester, Pennsylvania",
      "Honolulu, Hawaii",
      "Galveston, Texas",
      "Mobile, Alabama",
      "Atlanta, Georgia",
      "Portland, Oregon",
      "San Diego, California",
      "Gramercy, Louisiana",
      "West Palm Beach, Florida",
      "Gulfport, Mississippi",
      "Cleveland, Ohio",
      "Port Canaveral, Florida",
      "LOS ANGELES",
      "Port Hueneme, California",
      "Brunswick, Georgia",
      "Vancouver, Washington",
      "Chicago, Illinois"
   ],
   "notify":[
      "nan",
      "UPS CUSTOMS BROKERAGE",
      "UPS CUSTOMS BROKERAGESCHNEIDER LOGISTICS",
      "EXPEDITORS INTERNATIONAL OF",
      "FED EX TRADE NETWORKS",
      "EXPEDITORS INTERNATIONAL OF WASHINGSCHNEIDER LOGISTICS INCORPORATED",
      "EXPEDITORS INTERNATIONAL",
      "DAMCO CANADA INC",
      "SCHNEIDER LOGISTICS INCORPORATEDEXPEDITORS INTERNATIONAL OF WASHING",
      "EXPEDITORS INTERNATIONAL OF WASHINGSCHNEIDER LOGISTICS",
      "EXPEDITORS INTERNATIONAL OFSCHNEIDER LOGISTICS",
      "HPL HELLMANN PERISHABLE LOGISTICS",
      "UPS SUPPLY CHAIN SOLUTIONSSCHNEIDER LOGISTICS",
      "FEDEX TRADE NETWORKS TRANSPORT & BRSCHNEIDER LOGISTICS",
      "FEDEX TRADE NETWORKS",
      "EXPEDITORS INTL OF WA INC",
      "UPS BROKERAGE",
      "SCHNEIDER LOGISTICS ATTN: PETEREXPEDITORS INTERNATIONAL IAH",
      "EXPEDITORS INTERNATIONAL IAHSCHNEIDER LOGISTICS ATTN: PETER",
      "UPS SUPPLY CHAIN SOLUTIONSSCHNEIDER LOGISTICS INCORPORATED",
      "FEDEX TRADE NETWORKS (ORD)SCHNEIDER LOGISTICS",
      "UPS BROKERAGESCHNEIDER LOGISTICS",
      "FEDEX TRADE NETWORKSSCHNEIDER LOGISTICS",
      "SCHNEIDER LOGISTICS INCORPORATEDUPS SUPPLY CHAIN SOLUTIONS",
      "EXPEDITORS INTL- SAV"
   ],
   "vessel_name":[
      "MSC FLAVIA",
      "MSC ALTAIR",
      "MSC FRANCESCA",
      "CMA CGM NORMA",
      "MSC TOMOKO",
      "MSC SOLA",
      "CMA CGM LIBRA",
      "MOL MAXIM",
      "CMA CGM IVANHOE",
      "MAERSK ALTAIR",
      "PACIFIC LINK",
      "CMA CGM TANCREDI",
      "CMA CGM ORFEO",
      "COSCO CHINA",
      "COSCO JEDDAH",
      "MAERSK DANBURY",
      "CMA CGM VIVALDI",
      "CMA CGM TOSCA",
      "GERD MAERSK",
      "MAERSK DAMIETTA",
      "ARNOLD MAERSK",
      "COSCO PHILIPPINES",
      "MOL PRESTIGE",
      "CMA CGM CENTAURUS",
      "CMA CGM SAMSON"
   ],
   "ship_registered_in":[
      "PANAMA",
      "LIBERIA",
      "DENMARK",
      "HONG KONG",
      "UNITED KINGDOM",
      "MALTA",
      "GERMANY",
      "MARSHALL ISLANDS",
      "UNITED STATES",
      "SINGAPORE",
      "FRANCE",
      "ANTIGUA AND BARBUDA",
      "BAHAMAS",
      "GREECE",
      "CHINA",
      "PHILIPPINES",
      "CYPRUS",
      "NETHERLANDS",
      "ISRAEL",
      "BERMUDA",
      "NORWAY",
      "SWEDEN",
      "ITALY",
      "AUSTRIA",
      "KOREA, REPUBLIC OF",
      "TAIWAN, PROVINCE OF CHINA",
      "TURKEY",
      "LIBYAN ARAB JAMAHIRIYA",
      "SAUDI ARABIA",
      "COOK ISLANDS",
      "VANUATU",
      "JAPAN",
      "GEORGIA",
      "BAHRAIN",
      "UNITED ARAB EMIRATES",
      "BRAZIL",
      "nan",
      "QATAR",
      "CAYMAN ISLANDS",
      "AMERICAN SAMOA"
   ],
   "carrier_code":[
      "MAEU",
      "MSCU",
      "COSU",
      "CMDU",
      "HDMU",
      "MOLU",
      "EGLV",
      "HJSC",
      "SMLU",
      "OOLU",
      "HLCU",
      "APLU",
      "NYKS",
      "KKLU",
      "ZIMU",
      "BANQ",
      "NKLC",
      "EXDO",
      "CHIW",
      "YMLU",
      "CHNJ",
      "GSSW",
      "PLLU",
      "ACLU",
      "CSVV",
      "OERT",
      "DMCQ",
      "BBCH",
      "CGPN",
      "WWSU",
      "TOPO",
      "SUDU",
      "AMAW",
      "SAFM",
      "AAAG",
      "DEWC",
      "HNLT",
      "TRUM",
      "PNEP",
      "ANLC"
   ],
   "country_of_origin":[
      "China",
      "Hong Kong",
      "South Korea",
      "Singapore",
      "Oman",
      "Panama",
      "China Taiwan",
      "Malaysia",
      "Guatemala",
      "Spain",
      "Costa Rica",
      "India",
      "Japan",
      "Chile",
      "Sri Lanka",
      "Pakistan",
      "Germany",
      "Thailand",
      "Vietnam",
      "Mexico",
      "Italy",
      "Brazil",
      "Egypt",
      "American Samoa",
      "Bahamas",
      "Honduras",
      "Belgium",
      "Jamaica",
      "United Kingdom",
      "Sweden",
      "Canada",
      "Dominican Republic",
      "Netherlands",
      "Colombia",
      "Haiti",
      "France",
      "South Africa",
      "Israel",
      "Romania",
      "Greece"
   ]
}

categorical_fields = ["shipper", "consignee", "us_port", "notify", "vessel_name", "ship_registered_in", "carrier_code", "country_of_origin"]
numerical_fields = ["arrival_date", "weight_lb", "container_count"]
text_fields = ["product_details"]

